// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: greenfield/storage/v2/tx.proto

package v2

import (
	context "context"
	fmt "fmt"
	_ "github.com/bnb-chain/greenfield/types/common"
	_ "github.com/bnb-chain/greenfield/x/permission/types"
	types "github.com/bnb-chain/greenfield/x/storage/types"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateGroupV2 struct {
	// owner defines the account address of group owner who create the group
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	// group_name defines the name of the group. it's not globally unique.
	GroupName string `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	// member_request defines a list of member which to be add or remove
	Members []string `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	// extra defines extra info for the group
	Extra string `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	// members_with_expiration defines a list of member with expiration time
	MembersWithExpiration []*MsgGroupMember `protobuf:"bytes,5,rep,name=members_with_expiration,json=membersWithExpiration,proto3" json:"members_with_expiration,omitempty"`
}

func (m *MsgCreateGroupV2) Reset()         { *m = MsgCreateGroupV2{} }
func (m *MsgCreateGroupV2) String() string { return proto.CompactTextString(m) }
func (*MsgCreateGroupV2) ProtoMessage()    {}
func (*MsgCreateGroupV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4b2a5f03fff3226, []int{0}
}
func (m *MsgCreateGroupV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateGroupV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateGroupV2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateGroupV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateGroupV2.Merge(m, src)
}
func (m *MsgCreateGroupV2) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateGroupV2) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateGroupV2.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateGroupV2 proto.InternalMessageInfo

func (m *MsgCreateGroupV2) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateGroupV2) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *MsgCreateGroupV2) GetMembers() []string {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *MsgCreateGroupV2) GetExtra() string {
	if m != nil {
		return m.Extra
	}
	return ""
}

func (m *MsgCreateGroupV2) GetMembersWithExpiration() []*MsgGroupMember {
	if m != nil {
		return m.MembersWithExpiration
	}
	return nil
}

type MsgUpdateGroupMemberV2 struct {
	// operator defines the account address of the operator who has the UpdateGroupMember permission of the group.
	Operator string `protobuf:"bytes,1,opt,name=operator,proto3" json:"operator,omitempty"`
	// group_owner defines the account address of the group owner
	GroupOwner string `protobuf:"bytes,2,opt,name=group_owner,json=groupOwner,proto3" json:"group_owner,omitempty"`
	// group_name defines the name of the group which to be updated
	GroupName string `protobuf:"bytes,3,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	// members_to_add defines a list of members account address which will be add to the group
	MembersToAdd []string `protobuf:"bytes,4,rep,name=members_to_add,json=membersToAdd,proto3" json:"members_to_add,omitempty"`
	// members_to_delete defines a list of members account address which will be remove from the group
	MembersToDelete []string `protobuf:"bytes,5,rep,name=members_to_delete,json=membersToDelete,proto3" json:"members_to_delete,omitempty"`
	// members_with_expiration defines a list of member with expiration time
	MembersWithExpiration []*MsgGroupMember `protobuf:"bytes,6,rep,name=members_with_expiration,json=membersWithExpiration,proto3" json:"members_with_expiration,omitempty"`
}

func (m *MsgUpdateGroupMemberV2) Reset()         { *m = MsgUpdateGroupMemberV2{} }
func (m *MsgUpdateGroupMemberV2) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateGroupMemberV2) ProtoMessage()    {}
func (*MsgUpdateGroupMemberV2) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4b2a5f03fff3226, []int{1}
}
func (m *MsgUpdateGroupMemberV2) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateGroupMemberV2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateGroupMemberV2.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateGroupMemberV2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateGroupMemberV2.Merge(m, src)
}
func (m *MsgUpdateGroupMemberV2) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateGroupMemberV2) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateGroupMemberV2.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateGroupMemberV2 proto.InternalMessageInfo

func (m *MsgUpdateGroupMemberV2) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *MsgUpdateGroupMemberV2) GetGroupOwner() string {
	if m != nil {
		return m.GroupOwner
	}
	return ""
}

func (m *MsgUpdateGroupMemberV2) GetGroupName() string {
	if m != nil {
		return m.GroupName
	}
	return ""
}

func (m *MsgUpdateGroupMemberV2) GetMembersToAdd() []string {
	if m != nil {
		return m.MembersToAdd
	}
	return nil
}

func (m *MsgUpdateGroupMemberV2) GetMembersToDelete() []string {
	if m != nil {
		return m.MembersToDelete
	}
	return nil
}

func (m *MsgUpdateGroupMemberV2) GetMembersWithExpiration() []*MsgGroupMember {
	if m != nil {
		return m.MembersWithExpiration
	}
	return nil
}

type MsgGroupMember struct {
	// member defines the account address of the group member
	Member string `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	// expiration_time defines the expiration time of the group member
	ExpirationTime time.Time `protobuf:"bytes,2,opt,name=expiration_time,json=expirationTime,proto3,stdtime" json:"expiration_time"`
}

func (m *MsgGroupMember) Reset()         { *m = MsgGroupMember{} }
func (m *MsgGroupMember) String() string { return proto.CompactTextString(m) }
func (*MsgGroupMember) ProtoMessage()    {}
func (*MsgGroupMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4b2a5f03fff3226, []int{2}
}
func (m *MsgGroupMember) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgGroupMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgGroupMember.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgGroupMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgGroupMember.Merge(m, src)
}
func (m *MsgGroupMember) XXX_Size() int {
	return m.Size()
}
func (m *MsgGroupMember) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgGroupMember.DiscardUnknown(m)
}

var xxx_messageInfo_MsgGroupMember proto.InternalMessageInfo

func (m *MsgGroupMember) GetMember() string {
	if m != nil {
		return m.Member
	}
	return ""
}

func (m *MsgGroupMember) GetExpirationTime() time.Time {
	if m != nil {
		return m.ExpirationTime
	}
	return time.Time{}
}

func init() {
	proto.RegisterType((*MsgCreateGroupV2)(nil), "greenfield.storage.v2.MsgCreateGroupV2")
	proto.RegisterType((*MsgUpdateGroupMemberV2)(nil), "greenfield.storage.v2.MsgUpdateGroupMemberV2")
	proto.RegisterType((*MsgGroupMember)(nil), "greenfield.storage.v2.MsgGroupMember")
}

func init() { proto.RegisterFile("greenfield/storage/v2/tx.proto", fileDescriptor_d4b2a5f03fff3226) }

var fileDescriptor_d4b2a5f03fff3226 = []byte{
	// 1054 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x97, 0x41, 0x6f, 0xdc, 0x44,
	0x14, 0xc7, 0xb3, 0xdd, 0x36, 0x34, 0x93, 0x34, 0x6d, 0x4c, 0x42, 0x17, 0x23, 0x36, 0xcb, 0x02,
	0x6a, 0x48, 0x1b, 0x3b, 0x35, 0xbd, 0xc0, 0x01, 0xa9, 0x49, 0x2a, 0x84, 0xd4, 0xa5, 0xd1, 0xb6,
	0xb4, 0x52, 0xa5, 0x6a, 0xf1, 0xda, 0x13, 0xc7, 0xb0, 0xf6, 0x58, 0x33, 0xb3, 0x9b, 0x44, 0x9c,
	0xe0, 0x13, 0x94, 0x7b, 0x3f, 0x04, 0x07, 0x3e, 0x44, 0x8f, 0x15, 0x27, 0x4e, 0x80, 0x92, 0x03,
	0x5f, 0x03, 0xd9, 0x33, 0x1e, 0xcf, 0xae, 0x77, 0x3c, 0x46, 0xea, 0x29, 0xf1, 0xcc, 0xef, 0xbd,
	0xbf, 0xdf, 0x7b, 0xf3, 0xde, 0x8e, 0x41, 0x3b, 0xc0, 0x10, 0xc6, 0x47, 0x21, 0x1c, 0xf9, 0x36,
	0xa1, 0x08, 0xbb, 0x01, 0xb4, 0x27, 0x8e, 0x4d, 0x4f, 0xad, 0x04, 0x23, 0x8a, 0x8c, 0x8d, 0x62,
	0xdf, 0xe2, 0xfb, 0xd6, 0xc4, 0x31, 0x6f, 0x7a, 0x88, 0x44, 0x88, 0xd8, 0x11, 0x09, 0xec, 0xc9,
	0xdd, 0xf4, 0x0f, 0xe3, 0xcd, 0xf7, 0xd9, 0xc6, 0x20, 0x7b, 0xb2, 0xd9, 0x03, 0xdf, 0x5a, 0x0f,
	0x50, 0x80, 0xd8, 0x7a, 0xfa, 0x1f, 0x5f, 0xdd, 0x0c, 0x10, 0x0a, 0x46, 0xd0, 0xce, 0x9e, 0x86,
	0xe3, 0x23, 0x9b, 0x86, 0x11, 0x24, 0xd4, 0x8d, 0x12, 0x0e, 0x74, 0xa4, 0x37, 0xf4, 0x50, 0x14,
	0xa1, 0xd8, 0x76, 0x93, 0x04, 0xa3, 0x89, 0x3b, 0x12, 0x2e, 0x4a, 0xc4, 0x09, 0x76, 0x93, 0x04,
	0x62, 0x0e, 0x74, 0x25, 0x20, 0x81, 0x38, 0x0a, 0x09, 0x09, 0x51, 0xcc, 0xd9, 0x39, 0x4e, 0xf2,
	0x44, 0x68, 0x81, 0xc4, 0xc5, 0x6e, 0x94, 0xc7, 0x37, 0x2f, 0x95, 0xf4, 0x2c, 0x81, 0xf9, 0xfe,
	0x07, 0xf3, 0xf6, 0x79, 0x9e, 0xbb, 0xaf, 0x2e, 0x81, 0x1b, 0x3d, 0x12, 0xec, 0x63, 0xe8, 0x52,
	0xf8, 0x35, 0x46, 0xe3, 0xe4, 0xa9, 0x63, 0x38, 0xe0, 0x1d, 0x2f, 0x5d, 0x40, 0xb8, 0xd5, 0xe8,
	0x34, 0xb6, 0x96, 0xf6, 0x5a, 0x7f, 0xfc, 0xbe, 0xb3, 0xce, 0x93, 0x7a, 0xdf, 0xf7, 0x31, 0x24,
	0xe4, 0x31, 0xc5, 0x61, 0x1c, 0xf4, 0x73, 0xd0, 0xf8, 0x10, 0x80, 0x20, 0x35, 0x1f, 0xc4, 0x6e,
	0x04, 0x5b, 0x97, 0x52, 0xb3, 0xfe, 0x52, 0xb6, 0xf2, 0xad, 0x1b, 0xc1, 0xd4, 0x65, 0x04, 0xa3,
	0x21, 0xc4, 0xa4, 0xd5, 0xec, 0x34, 0xab, 0x5d, 0x72, 0xd0, 0x58, 0x07, 0x57, 0xe0, 0x29, 0xc5,
	0x6e, 0xeb, 0x72, 0xe6, 0x8d, 0x3d, 0x18, 0x2f, 0xc0, 0x4d, 0x0e, 0x0c, 0x4e, 0x42, 0x7a, 0x3c,
	0x80, 0xa7, 0x49, 0x88, 0x5d, 0x1a, 0xa2, 0xb8, 0x75, 0xa5, 0xd3, 0xdc, 0x5a, 0x76, 0x3e, 0xb5,
	0xe6, 0x9e, 0x1d, 0xab, 0x47, 0x82, 0x2c, 0xc0, 0x5e, 0x66, 0xdd, 0xdf, 0xe0, 0x5e, 0x9e, 0x85,
	0xf4, 0xf8, 0x81, 0xf0, 0xf1, 0xe5, 0xca, 0x2f, 0xff, 0xfe, 0xb6, 0x9d, 0x47, 0xd5, 0x7d, 0xd5,
	0x04, 0xef, 0xf5, 0x48, 0xf0, 0x5d, 0xe2, 0xe7, 0xe9, 0x61, 0xd6, 0x4f, 0x1d, 0xe3, 0x1e, 0xb8,
	0x8a, 0x12, 0x88, 0x6b, 0x65, 0x49, 0x90, 0xc6, 0x17, 0x60, 0x99, 0xa5, 0x09, 0x9d, 0xc4, 0x10,
	0xb3, 0x3c, 0x55, 0x18, 0xb2, 0x9c, 0x3e, 0x4a, 0xd9, 0x99, 0x0c, 0x37, 0x67, 0x33, 0xfc, 0x15,
	0x58, 0xcd, 0xf3, 0x42, 0xd1, 0xc0, 0xf5, 0xfd, 0xd6, 0x65, 0x4d, 0xa2, 0x57, 0x38, 0xff, 0x04,
	0xdd, 0xf7, 0x7d, 0xe3, 0x00, 0xac, 0x49, 0xf6, 0x3e, 0x1c, 0x41, 0x0a, 0xb3, 0x8c, 0x56, 0xb9,
	0xb8, 0x2e, 0x5c, 0x1c, 0x64, 0x06, 0x55, 0xd5, 0x59, 0x7c, 0x0b, 0xd5, 0xb9, 0x96, 0x56, 0x47,
	0x64, 0xb3, 0xfb, 0x6b, 0x03, 0xac, 0x4e, 0x1b, 0x1a, 0xbb, 0x60, 0x91, 0x99, 0x6a, 0x8b, 0xc2,
	0x39, 0xa3, 0x07, 0xae, 0x17, 0x6f, 0x39, 0x48, 0xc7, 0x40, 0x56, 0x96, 0x65, 0xc7, 0xb4, 0xd8,
	0x8c, 0xb0, 0xf2, 0x19, 0x61, 0x3d, 0xc9, 0x67, 0xc4, 0xde, 0xd5, 0xd7, 0x7f, 0x6d, 0x2e, 0xbc,
	0xfc, 0x7b, 0xb3, 0xd1, 0x5f, 0x2d, 0x8c, 0xd3, 0x6d, 0xe7, 0xe7, 0x0d, 0xd0, 0xec, 0x91, 0xc0,
	0xf8, 0x1e, 0xac, 0xb0, 0xae, 0xda, 0x1b, 0x7b, 0x3f, 0x42, 0x6a, 0x7c, 0x3c, 0x2f, 0x70, 0xd1,
	0x7a, 0x0c, 0x32, 0x6f, 0xd7, 0x80, 0xfa, 0x90, 0x24, 0x28, 0x26, 0x30, 0x55, 0x60, 0x59, 0xd7,
	0x28, 0xc8, 0x90, 0x52, 0x41, 0x86, 0x84, 0xc2, 0x08, 0xdc, 0x60, 0x47, 0x9f, 0xad, 0x7f, 0x13,
	0x1f, 0x21, 0xe3, 0x96, 0xc2, 0xc1, 0x2c, 0x68, 0xda, 0x35, 0x41, 0x39, 0x9e, 0x5e, 0x88, 0x31,
	0xc2, 0x9a, 0x78, 0x64, 0x48, 0x19, 0x8f, 0x0c, 0x09, 0x05, 0x04, 0xd6, 0x0e, 0x42, 0xe2, 0xa1,
	0x98, 0x86, 0xf1, 0x38, 0x4f, 0xdb, 0x96, 0x2a, 0x23, 0xb3, 0xa4, 0xb9, 0x5b, 0x97, 0x94, 0x43,
	0x62, 0xa5, 0x7b, 0x34, 0xfc, 0x01, 0x7a, 0xba, 0x43, 0xc0, 0x20, 0xcd, 0x21, 0x60, 0x90, 0x50,
	0x78, 0x0e, 0xc0, 0x63, 0xe8, 0x8e, 0xb8, 0xff, 0x8f, 0x14, 0xa6, 0x05, 0x62, 0x7e, 0xa6, 0x45,
	0xe4, 0xf2, 0xf7, 0x61, 0xba, 0x22, 0x29, 0xa8, 0xca, 0x3f, 0x0b, 0x2a, 0xcb, 0x3f, 0x0b, 0xca,
	0x91, 0xec, 0xa3, 0xe4, 0x4c, 0x13, 0x49, 0x81, 0x28, 0x23, 0x29, 0x90, 0x72, 0xab, 0x68, 0xea,
	0x20, 0x43, 0x9a, 0x56, 0x99, 0x51, 0xc0, 0xc0, 0xd8, 0x77, 0x63, 0x0f, 0x8e, 0xa6, 0xea, 0xad,
	0x7c, 0xc5, 0x12, 0x6a, 0xde, 0xad, 0x8d, 0x96, 0x1b, 0x46, 0x13, 0x95, 0x0c, 0x69, 0x1a, 0x66,
	0x46, 0x61, 0xba, 0x61, 0xb8, 0x4c, 0x8d, 0x86, 0xe1, 0x5a, 0xbb, 0x75, 0xc9, 0xf2, 0xc4, 0x61,
	0xeb, 0x35, 0x26, 0x4e, 0x01, 0x6a, 0x26, 0x4e, 0x01, 0x0a, 0xb5, 0x21, 0x58, 0x96, 0x6e, 0x3e,
	0xf3, 0x85, 0xd8, 0x6f, 0xd3, 0xd4, 0x05, 0xc9, 0xdc, 0xae, 0xec, 0xd0, 0x8c, 0x12, 0x1a, 0x2f,
	0xc0, 0x32, 0x3b, 0x30, 0x4c, 0xa3, 0x5b, 0x79, 0xa8, 0x32, 0x46, 0xe9, 0x5e, 0x62, 0x84, 0x7b,
	0x0a, 0xd6, 0x4a, 0xb7, 0x13, 0x63, 0x47, 0x1d, 0xc8, 0x9c, 0xab, 0x8c, 0xb2, 0x4c, 0x25, 0xb6,
	0x5c, 0xa6, 0x6c, 0xf3, 0x41, 0x76, 0x31, 0xbb, 0xa5, 0xf7, 0x92, 0x81, 0x9a, 0x32, 0x15, 0xa0,
	0x3c, 0x19, 0x1e, 0x42, 0x77, 0xc2, 0x33, 0xa8, 0x9a, 0x0c, 0x05, 0xa2, 0x9c, 0x0c, 0x05, 0x22,
	0x97, 0x87, 0x9d, 0xfc, 0xea, 0xf2, 0x48, 0x8c, 0xb2, 0x3c, 0x12, 0x23, 0xdc, 0x3f, 0x03, 0x4b,
	0x87, 0x63, 0x7a, 0x88, 0x46, 0xa1, 0x77, 0x66, 0x74, 0x14, 0x86, 0x82, 0x30, 0xb7, 0x74, 0x44,
	0x79, 0xa2, 0x71, 0xdf, 0xd5, 0x13, 0x8d, 0xbb, 0xbf, 0x5d, 0x03, 0x92, 0x15, 0x58, 0x45, 0x0e,
	0xb3, 0xaf, 0x0d, 0xa5, 0x82, 0x0c, 0x29, 0x15, 0x64, 0x48, 0x28, 0x78, 0xe0, 0x5a, 0x2f, 0x0c,
	0x70, 0x71, 0x47, 0xfa, 0x44, 0x99, 0x59, 0x89, 0x32, 0xef, 0xd4, 0xa1, 0x84, 0xc8, 0x4f, 0x60,
	0x63, 0x1f, 0x45, 0x49, 0x1a, 0xe0, 0xb4, 0xd8, 0x1d, 0xe5, 0xcf, 0xc7, 0x1c, 0xda, 0xbc, 0xf7,
	0x7f, 0x68, 0x21, 0x3e, 0x06, 0xef, 0xb2, 0xf9, 0x3d, 0x2d, 0xbd, 0x5d, 0x39, 0xeb, 0xa7, 0x85,
	0x9d, 0xfa, 0x6c, 0x2e, 0xbb, 0xf7, 0xf0, 0xf5, 0x79, 0xbb, 0xf1, 0xe6, 0xbc, 0xdd, 0xf8, 0xe7,
	0xbc, 0xdd, 0x78, 0x79, 0xd1, 0x5e, 0x78, 0x73, 0xd1, 0x5e, 0xf8, 0xf3, 0xa2, 0xbd, 0xf0, 0xdc,
	0x09, 0x42, 0x7a, 0x3c, 0x1e, 0x5a, 0x1e, 0x8a, 0xec, 0x61, 0x3c, 0xdc, 0xf1, 0x8e, 0xdd, 0x30,
	0xb6, 0xa5, 0x2f, 0xc4, 0xd3, 0xe9, 0x6f, 0x48, 0x7b, 0xe2, 0x0c, 0x17, 0xb3, 0xfb, 0xef, 0xe7,
	0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xe6, 0xfa, 0xc6, 0xec, 0xb4, 0x0f, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// basic operation of bucket
	CreateBucket(ctx context.Context, in *types.MsgCreateBucket, opts ...grpc.CallOption) (*types.MsgCreateBucketResponse, error)
	DeleteBucket(ctx context.Context, in *types.MsgDeleteBucket, opts ...grpc.CallOption) (*types.MsgDeleteBucketResponse, error)
	UpdateBucketInfo(ctx context.Context, in *types.MsgUpdateBucketInfo, opts ...grpc.CallOption) (*types.MsgUpdateBucketInfoResponse, error)
	MirrorBucket(ctx context.Context, in *types.MsgMirrorBucket, opts ...grpc.CallOption) (*types.MsgMirrorBucketResponse, error)
	DiscontinueBucket(ctx context.Context, in *types.MsgDiscontinueBucket, opts ...grpc.CallOption) (*types.MsgDiscontinueBucketResponse, error)
	// basic operation of object
	CreateObject(ctx context.Context, in *types.MsgCreateObject, opts ...grpc.CallOption) (*types.MsgCreateObjectResponse, error)
	SealObject(ctx context.Context, in *types.MsgSealObject, opts ...grpc.CallOption) (*types.MsgSealObjectResponse, error)
	RejectSealObject(ctx context.Context, in *types.MsgRejectSealObject, opts ...grpc.CallOption) (*types.MsgRejectSealObjectResponse, error)
	CopyObject(ctx context.Context, in *types.MsgCopyObject, opts ...grpc.CallOption) (*types.MsgCopyObjectResponse, error)
	DeleteObject(ctx context.Context, in *types.MsgDeleteObject, opts ...grpc.CallOption) (*types.MsgDeleteObjectResponse, error)
	CancelCreateObject(ctx context.Context, in *types.MsgCancelCreateObject, opts ...grpc.CallOption) (*types.MsgCancelCreateObjectResponse, error)
	MirrorObject(ctx context.Context, in *types.MsgMirrorObject, opts ...grpc.CallOption) (*types.MsgMirrorObjectResponse, error)
	DiscontinueObject(ctx context.Context, in *types.MsgDiscontinueObject, opts ...grpc.CallOption) (*types.MsgDiscontinueObjectResponse, error)
	UpdateObjectInfo(ctx context.Context, in *types.MsgUpdateObjectInfo, opts ...grpc.CallOption) (*types.MsgUpdateObjectInfoResponse, error)
	// basic operation of group
	CreateGroup(ctx context.Context, in *MsgCreateGroupV2, opts ...grpc.CallOption) (*types.MsgCreateGroupResponse, error)
	DeleteGroup(ctx context.Context, in *types.MsgDeleteGroup, opts ...grpc.CallOption) (*types.MsgDeleteGroupResponse, error)
	UpdateGroupMember(ctx context.Context, in *MsgUpdateGroupMemberV2, opts ...grpc.CallOption) (*types.MsgUpdateGroupMemberResponse, error)
	UpdateGroupExtra(ctx context.Context, in *types.MsgUpdateGroupExtra, opts ...grpc.CallOption) (*types.MsgUpdateGroupExtraResponse, error)
	LeaveGroup(ctx context.Context, in *types.MsgLeaveGroup, opts ...grpc.CallOption) (*types.MsgLeaveGroupResponse, error)
	MirrorGroup(ctx context.Context, in *types.MsgMirrorGroup, opts ...grpc.CallOption) (*types.MsgMirrorGroupResponse, error)
	// basic operation of policy
	PutPolicy(ctx context.Context, in *types.MsgPutPolicy, opts ...grpc.CallOption) (*types.MsgPutPolicyResponse, error)
	DeletePolicy(ctx context.Context, in *types.MsgDeletePolicy, opts ...grpc.CallOption) (*types.MsgDeletePolicyResponse, error)
	// Since: cosmos-sdk 0.47
	UpdateParams(ctx context.Context, in *types.MsgUpdateParams, opts ...grpc.CallOption) (*types.MsgUpdateParamsResponse, error)
	// this line is used by starport scaffolding # proto/tx/rpc
	MigrateBucket(ctx context.Context, in *types.MsgMigrateBucket, opts ...grpc.CallOption) (*types.MsgMigrateBucketResponse, error)
	CompleteMigrateBucket(ctx context.Context, in *types.MsgCompleteMigrateBucket, opts ...grpc.CallOption) (*types.MsgCompleteMigrateBucketResponse, error)
	CancelMigrateBucket(ctx context.Context, in *types.MsgCancelMigrateBucket, opts ...grpc.CallOption) (*types.MsgCancelMigrateBucketResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateBucket(ctx context.Context, in *types.MsgCreateBucket, opts ...grpc.CallOption) (*types.MsgCreateBucketResponse, error) {
	out := new(types.MsgCreateBucketResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/CreateBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteBucket(ctx context.Context, in *types.MsgDeleteBucket, opts ...grpc.CallOption) (*types.MsgDeleteBucketResponse, error) {
	out := new(types.MsgDeleteBucketResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/DeleteBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateBucketInfo(ctx context.Context, in *types.MsgUpdateBucketInfo, opts ...grpc.CallOption) (*types.MsgUpdateBucketInfoResponse, error) {
	out := new(types.MsgUpdateBucketInfoResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/UpdateBucketInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MirrorBucket(ctx context.Context, in *types.MsgMirrorBucket, opts ...grpc.CallOption) (*types.MsgMirrorBucketResponse, error) {
	out := new(types.MsgMirrorBucketResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/MirrorBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DiscontinueBucket(ctx context.Context, in *types.MsgDiscontinueBucket, opts ...grpc.CallOption) (*types.MsgDiscontinueBucketResponse, error) {
	out := new(types.MsgDiscontinueBucketResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/DiscontinueBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateObject(ctx context.Context, in *types.MsgCreateObject, opts ...grpc.CallOption) (*types.MsgCreateObjectResponse, error) {
	out := new(types.MsgCreateObjectResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/CreateObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SealObject(ctx context.Context, in *types.MsgSealObject, opts ...grpc.CallOption) (*types.MsgSealObjectResponse, error) {
	out := new(types.MsgSealObjectResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/SealObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) RejectSealObject(ctx context.Context, in *types.MsgRejectSealObject, opts ...grpc.CallOption) (*types.MsgRejectSealObjectResponse, error) {
	out := new(types.MsgRejectSealObjectResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/RejectSealObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CopyObject(ctx context.Context, in *types.MsgCopyObject, opts ...grpc.CallOption) (*types.MsgCopyObjectResponse, error) {
	out := new(types.MsgCopyObjectResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/CopyObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteObject(ctx context.Context, in *types.MsgDeleteObject, opts ...grpc.CallOption) (*types.MsgDeleteObjectResponse, error) {
	out := new(types.MsgDeleteObjectResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/DeleteObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelCreateObject(ctx context.Context, in *types.MsgCancelCreateObject, opts ...grpc.CallOption) (*types.MsgCancelCreateObjectResponse, error) {
	out := new(types.MsgCancelCreateObjectResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/CancelCreateObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MirrorObject(ctx context.Context, in *types.MsgMirrorObject, opts ...grpc.CallOption) (*types.MsgMirrorObjectResponse, error) {
	out := new(types.MsgMirrorObjectResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/MirrorObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DiscontinueObject(ctx context.Context, in *types.MsgDiscontinueObject, opts ...grpc.CallOption) (*types.MsgDiscontinueObjectResponse, error) {
	out := new(types.MsgDiscontinueObjectResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/DiscontinueObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateObjectInfo(ctx context.Context, in *types.MsgUpdateObjectInfo, opts ...grpc.CallOption) (*types.MsgUpdateObjectInfoResponse, error) {
	out := new(types.MsgUpdateObjectInfoResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/UpdateObjectInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateGroup(ctx context.Context, in *MsgCreateGroupV2, opts ...grpc.CallOption) (*types.MsgCreateGroupResponse, error) {
	out := new(types.MsgCreateGroupResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/CreateGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteGroup(ctx context.Context, in *types.MsgDeleteGroup, opts ...grpc.CallOption) (*types.MsgDeleteGroupResponse, error) {
	out := new(types.MsgDeleteGroupResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/DeleteGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateGroupMember(ctx context.Context, in *MsgUpdateGroupMemberV2, opts ...grpc.CallOption) (*types.MsgUpdateGroupMemberResponse, error) {
	out := new(types.MsgUpdateGroupMemberResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/UpdateGroupMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateGroupExtra(ctx context.Context, in *types.MsgUpdateGroupExtra, opts ...grpc.CallOption) (*types.MsgUpdateGroupExtraResponse, error) {
	out := new(types.MsgUpdateGroupExtraResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/UpdateGroupExtra", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) LeaveGroup(ctx context.Context, in *types.MsgLeaveGroup, opts ...grpc.CallOption) (*types.MsgLeaveGroupResponse, error) {
	out := new(types.MsgLeaveGroupResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/LeaveGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MirrorGroup(ctx context.Context, in *types.MsgMirrorGroup, opts ...grpc.CallOption) (*types.MsgMirrorGroupResponse, error) {
	out := new(types.MsgMirrorGroupResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/MirrorGroup", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) PutPolicy(ctx context.Context, in *types.MsgPutPolicy, opts ...grpc.CallOption) (*types.MsgPutPolicyResponse, error) {
	out := new(types.MsgPutPolicyResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/PutPolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeletePolicy(ctx context.Context, in *types.MsgDeletePolicy, opts ...grpc.CallOption) (*types.MsgDeletePolicyResponse, error) {
	out := new(types.MsgDeletePolicyResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/DeletePolicy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateParams(ctx context.Context, in *types.MsgUpdateParams, opts ...grpc.CallOption) (*types.MsgUpdateParamsResponse, error) {
	out := new(types.MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MigrateBucket(ctx context.Context, in *types.MsgMigrateBucket, opts ...grpc.CallOption) (*types.MsgMigrateBucketResponse, error) {
	out := new(types.MsgMigrateBucketResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/MigrateBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CompleteMigrateBucket(ctx context.Context, in *types.MsgCompleteMigrateBucket, opts ...grpc.CallOption) (*types.MsgCompleteMigrateBucketResponse, error) {
	out := new(types.MsgCompleteMigrateBucketResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/CompleteMigrateBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CancelMigrateBucket(ctx context.Context, in *types.MsgCancelMigrateBucket, opts ...grpc.CallOption) (*types.MsgCancelMigrateBucketResponse, error) {
	out := new(types.MsgCancelMigrateBucketResponse)
	err := c.cc.Invoke(ctx, "/greenfield.storage.v2.Msg/CancelMigrateBucket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// basic operation of bucket
	CreateBucket(context.Context, *types.MsgCreateBucket) (*types.MsgCreateBucketResponse, error)
	DeleteBucket(context.Context, *types.MsgDeleteBucket) (*types.MsgDeleteBucketResponse, error)
	UpdateBucketInfo(context.Context, *types.MsgUpdateBucketInfo) (*types.MsgUpdateBucketInfoResponse, error)
	MirrorBucket(context.Context, *types.MsgMirrorBucket) (*types.MsgMirrorBucketResponse, error)
	DiscontinueBucket(context.Context, *types.MsgDiscontinueBucket) (*types.MsgDiscontinueBucketResponse, error)
	// basic operation of object
	CreateObject(context.Context, *types.MsgCreateObject) (*types.MsgCreateObjectResponse, error)
	SealObject(context.Context, *types.MsgSealObject) (*types.MsgSealObjectResponse, error)
	RejectSealObject(context.Context, *types.MsgRejectSealObject) (*types.MsgRejectSealObjectResponse, error)
	CopyObject(context.Context, *types.MsgCopyObject) (*types.MsgCopyObjectResponse, error)
	DeleteObject(context.Context, *types.MsgDeleteObject) (*types.MsgDeleteObjectResponse, error)
	CancelCreateObject(context.Context, *types.MsgCancelCreateObject) (*types.MsgCancelCreateObjectResponse, error)
	MirrorObject(context.Context, *types.MsgMirrorObject) (*types.MsgMirrorObjectResponse, error)
	DiscontinueObject(context.Context, *types.MsgDiscontinueObject) (*types.MsgDiscontinueObjectResponse, error)
	UpdateObjectInfo(context.Context, *types.MsgUpdateObjectInfo) (*types.MsgUpdateObjectInfoResponse, error)
	// basic operation of group
	CreateGroup(context.Context, *MsgCreateGroupV2) (*types.MsgCreateGroupResponse, error)
	DeleteGroup(context.Context, *types.MsgDeleteGroup) (*types.MsgDeleteGroupResponse, error)
	UpdateGroupMember(context.Context, *MsgUpdateGroupMemberV2) (*types.MsgUpdateGroupMemberResponse, error)
	UpdateGroupExtra(context.Context, *types.MsgUpdateGroupExtra) (*types.MsgUpdateGroupExtraResponse, error)
	LeaveGroup(context.Context, *types.MsgLeaveGroup) (*types.MsgLeaveGroupResponse, error)
	MirrorGroup(context.Context, *types.MsgMirrorGroup) (*types.MsgMirrorGroupResponse, error)
	// basic operation of policy
	PutPolicy(context.Context, *types.MsgPutPolicy) (*types.MsgPutPolicyResponse, error)
	DeletePolicy(context.Context, *types.MsgDeletePolicy) (*types.MsgDeletePolicyResponse, error)
	// Since: cosmos-sdk 0.47
	UpdateParams(context.Context, *types.MsgUpdateParams) (*types.MsgUpdateParamsResponse, error)
	// this line is used by starport scaffolding # proto/tx/rpc
	MigrateBucket(context.Context, *types.MsgMigrateBucket) (*types.MsgMigrateBucketResponse, error)
	CompleteMigrateBucket(context.Context, *types.MsgCompleteMigrateBucket) (*types.MsgCompleteMigrateBucketResponse, error)
	CancelMigrateBucket(context.Context, *types.MsgCancelMigrateBucket) (*types.MsgCancelMigrateBucketResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateBucket(ctx context.Context, req *types.MsgCreateBucket) (*types.MsgCreateBucketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBucket not implemented")
}
func (*UnimplementedMsgServer) DeleteBucket(ctx context.Context, req *types.MsgDeleteBucket) (*types.MsgDeleteBucketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBucket not implemented")
}
func (*UnimplementedMsgServer) UpdateBucketInfo(ctx context.Context, req *types.MsgUpdateBucketInfo) (*types.MsgUpdateBucketInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBucketInfo not implemented")
}
func (*UnimplementedMsgServer) MirrorBucket(ctx context.Context, req *types.MsgMirrorBucket) (*types.MsgMirrorBucketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MirrorBucket not implemented")
}
func (*UnimplementedMsgServer) DiscontinueBucket(ctx context.Context, req *types.MsgDiscontinueBucket) (*types.MsgDiscontinueBucketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscontinueBucket not implemented")
}
func (*UnimplementedMsgServer) CreateObject(ctx context.Context, req *types.MsgCreateObject) (*types.MsgCreateObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateObject not implemented")
}
func (*UnimplementedMsgServer) SealObject(ctx context.Context, req *types.MsgSealObject) (*types.MsgSealObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SealObject not implemented")
}
func (*UnimplementedMsgServer) RejectSealObject(ctx context.Context, req *types.MsgRejectSealObject) (*types.MsgRejectSealObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectSealObject not implemented")
}
func (*UnimplementedMsgServer) CopyObject(ctx context.Context, req *types.MsgCopyObject) (*types.MsgCopyObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CopyObject not implemented")
}
func (*UnimplementedMsgServer) DeleteObject(ctx context.Context, req *types.MsgDeleteObject) (*types.MsgDeleteObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteObject not implemented")
}
func (*UnimplementedMsgServer) CancelCreateObject(ctx context.Context, req *types.MsgCancelCreateObject) (*types.MsgCancelCreateObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelCreateObject not implemented")
}
func (*UnimplementedMsgServer) MirrorObject(ctx context.Context, req *types.MsgMirrorObject) (*types.MsgMirrorObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MirrorObject not implemented")
}
func (*UnimplementedMsgServer) DiscontinueObject(ctx context.Context, req *types.MsgDiscontinueObject) (*types.MsgDiscontinueObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiscontinueObject not implemented")
}
func (*UnimplementedMsgServer) UpdateObjectInfo(ctx context.Context, req *types.MsgUpdateObjectInfo) (*types.MsgUpdateObjectInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateObjectInfo not implemented")
}
func (*UnimplementedMsgServer) CreateGroup(ctx context.Context, req *MsgCreateGroupV2) (*types.MsgCreateGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGroup not implemented")
}
func (*UnimplementedMsgServer) DeleteGroup(ctx context.Context, req *types.MsgDeleteGroup) (*types.MsgDeleteGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGroup not implemented")
}
func (*UnimplementedMsgServer) UpdateGroupMember(ctx context.Context, req *MsgUpdateGroupMemberV2) (*types.MsgUpdateGroupMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroupMember not implemented")
}
func (*UnimplementedMsgServer) UpdateGroupExtra(ctx context.Context, req *types.MsgUpdateGroupExtra) (*types.MsgUpdateGroupExtraResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateGroupExtra not implemented")
}
func (*UnimplementedMsgServer) LeaveGroup(ctx context.Context, req *types.MsgLeaveGroup) (*types.MsgLeaveGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveGroup not implemented")
}
func (*UnimplementedMsgServer) MirrorGroup(ctx context.Context, req *types.MsgMirrorGroup) (*types.MsgMirrorGroupResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MirrorGroup not implemented")
}
func (*UnimplementedMsgServer) PutPolicy(ctx context.Context, req *types.MsgPutPolicy) (*types.MsgPutPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutPolicy not implemented")
}
func (*UnimplementedMsgServer) DeletePolicy(ctx context.Context, req *types.MsgDeletePolicy) (*types.MsgDeletePolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePolicy not implemented")
}
func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *types.MsgUpdateParams) (*types.MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) MigrateBucket(ctx context.Context, req *types.MsgMigrateBucket) (*types.MsgMigrateBucketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MigrateBucket not implemented")
}
func (*UnimplementedMsgServer) CompleteMigrateBucket(ctx context.Context, req *types.MsgCompleteMigrateBucket) (*types.MsgCompleteMigrateBucketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteMigrateBucket not implemented")
}
func (*UnimplementedMsgServer) CancelMigrateBucket(ctx context.Context, req *types.MsgCancelMigrateBucket) (*types.MsgCancelMigrateBucketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelMigrateBucket not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgCreateBucket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/CreateBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateBucket(ctx, req.(*types.MsgCreateBucket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgDeleteBucket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/DeleteBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteBucket(ctx, req.(*types.MsgDeleteBucket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateBucketInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgUpdateBucketInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateBucketInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/UpdateBucketInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateBucketInfo(ctx, req.(*types.MsgUpdateBucketInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MirrorBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgMirrorBucket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MirrorBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/MirrorBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MirrorBucket(ctx, req.(*types.MsgMirrorBucket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DiscontinueBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgDiscontinueBucket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DiscontinueBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/DiscontinueBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DiscontinueBucket(ctx, req.(*types.MsgDiscontinueBucket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgCreateObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/CreateObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateObject(ctx, req.(*types.MsgCreateObject))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SealObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgSealObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SealObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/SealObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SealObject(ctx, req.(*types.MsgSealObject))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_RejectSealObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgRejectSealObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).RejectSealObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/RejectSealObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).RejectSealObject(ctx, req.(*types.MsgRejectSealObject))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CopyObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgCopyObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CopyObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/CopyObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CopyObject(ctx, req.(*types.MsgCopyObject))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgDeleteObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/DeleteObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteObject(ctx, req.(*types.MsgDeleteObject))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelCreateObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgCancelCreateObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelCreateObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/CancelCreateObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelCreateObject(ctx, req.(*types.MsgCancelCreateObject))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MirrorObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgMirrorObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MirrorObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/MirrorObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MirrorObject(ctx, req.(*types.MsgMirrorObject))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DiscontinueObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgDiscontinueObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DiscontinueObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/DiscontinueObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DiscontinueObject(ctx, req.(*types.MsgDiscontinueObject))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateObjectInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgUpdateObjectInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateObjectInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/UpdateObjectInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateObjectInfo(ctx, req.(*types.MsgUpdateObjectInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateGroupV2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/CreateGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateGroup(ctx, req.(*MsgCreateGroupV2))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgDeleteGroup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/DeleteGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteGroup(ctx, req.(*types.MsgDeleteGroup))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateGroupMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateGroupMemberV2)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateGroupMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/UpdateGroupMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateGroupMember(ctx, req.(*MsgUpdateGroupMemberV2))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateGroupExtra_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgUpdateGroupExtra)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateGroupExtra(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/UpdateGroupExtra",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateGroupExtra(ctx, req.(*types.MsgUpdateGroupExtra))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_LeaveGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgLeaveGroup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).LeaveGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/LeaveGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).LeaveGroup(ctx, req.(*types.MsgLeaveGroup))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MirrorGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgMirrorGroup)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MirrorGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/MirrorGroup",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MirrorGroup(ctx, req.(*types.MsgMirrorGroup))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_PutPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgPutPolicy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).PutPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/PutPolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).PutPolicy(ctx, req.(*types.MsgPutPolicy))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeletePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgDeletePolicy)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeletePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/DeletePolicy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeletePolicy(ctx, req.(*types.MsgDeletePolicy))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*types.MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MigrateBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgMigrateBucket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MigrateBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/MigrateBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MigrateBucket(ctx, req.(*types.MsgMigrateBucket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CompleteMigrateBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgCompleteMigrateBucket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CompleteMigrateBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/CompleteMigrateBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CompleteMigrateBucket(ctx, req.(*types.MsgCompleteMigrateBucket))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CancelMigrateBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(types.MsgCancelMigrateBucket)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CancelMigrateBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greenfield.storage.v2.Msg/CancelMigrateBucket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CancelMigrateBucket(ctx, req.(*types.MsgCancelMigrateBucket))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greenfield.storage.v2.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBucket",
			Handler:    _Msg_CreateBucket_Handler,
		},
		{
			MethodName: "DeleteBucket",
			Handler:    _Msg_DeleteBucket_Handler,
		},
		{
			MethodName: "UpdateBucketInfo",
			Handler:    _Msg_UpdateBucketInfo_Handler,
		},
		{
			MethodName: "MirrorBucket",
			Handler:    _Msg_MirrorBucket_Handler,
		},
		{
			MethodName: "DiscontinueBucket",
			Handler:    _Msg_DiscontinueBucket_Handler,
		},
		{
			MethodName: "CreateObject",
			Handler:    _Msg_CreateObject_Handler,
		},
		{
			MethodName: "SealObject",
			Handler:    _Msg_SealObject_Handler,
		},
		{
			MethodName: "RejectSealObject",
			Handler:    _Msg_RejectSealObject_Handler,
		},
		{
			MethodName: "CopyObject",
			Handler:    _Msg_CopyObject_Handler,
		},
		{
			MethodName: "DeleteObject",
			Handler:    _Msg_DeleteObject_Handler,
		},
		{
			MethodName: "CancelCreateObject",
			Handler:    _Msg_CancelCreateObject_Handler,
		},
		{
			MethodName: "MirrorObject",
			Handler:    _Msg_MirrorObject_Handler,
		},
		{
			MethodName: "DiscontinueObject",
			Handler:    _Msg_DiscontinueObject_Handler,
		},
		{
			MethodName: "UpdateObjectInfo",
			Handler:    _Msg_UpdateObjectInfo_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _Msg_CreateGroup_Handler,
		},
		{
			MethodName: "DeleteGroup",
			Handler:    _Msg_DeleteGroup_Handler,
		},
		{
			MethodName: "UpdateGroupMember",
			Handler:    _Msg_UpdateGroupMember_Handler,
		},
		{
			MethodName: "UpdateGroupExtra",
			Handler:    _Msg_UpdateGroupExtra_Handler,
		},
		{
			MethodName: "LeaveGroup",
			Handler:    _Msg_LeaveGroup_Handler,
		},
		{
			MethodName: "MirrorGroup",
			Handler:    _Msg_MirrorGroup_Handler,
		},
		{
			MethodName: "PutPolicy",
			Handler:    _Msg_PutPolicy_Handler,
		},
		{
			MethodName: "DeletePolicy",
			Handler:    _Msg_DeletePolicy_Handler,
		},
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "MigrateBucket",
			Handler:    _Msg_MigrateBucket_Handler,
		},
		{
			MethodName: "CompleteMigrateBucket",
			Handler:    _Msg_CompleteMigrateBucket_Handler,
		},
		{
			MethodName: "CancelMigrateBucket",
			Handler:    _Msg_CancelMigrateBucket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "greenfield/storage/v2/tx.proto",
}

func (m *MsgCreateGroupV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateGroupV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateGroupV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MembersWithExpiration) > 0 {
		for iNdEx := len(m.MembersWithExpiration) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MembersWithExpiration[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.Extra) > 0 {
		i -= len(m.Extra)
		copy(dAtA[i:], m.Extra)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Extra)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Members) > 0 {
		for iNdEx := len(m.Members) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Members[iNdEx])
			copy(dAtA[i:], m.Members[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Members[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.GroupName) > 0 {
		i -= len(m.GroupName)
		copy(dAtA[i:], m.GroupName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.GroupName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateGroupMemberV2) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateGroupMemberV2) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateGroupMemberV2) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MembersWithExpiration) > 0 {
		for iNdEx := len(m.MembersWithExpiration) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MembersWithExpiration[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.MembersToDelete) > 0 {
		for iNdEx := len(m.MembersToDelete) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.MembersToDelete[iNdEx])
			copy(dAtA[i:], m.MembersToDelete[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.MembersToDelete[iNdEx])))
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.MembersToAdd) > 0 {
		for iNdEx := len(m.MembersToAdd) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.MembersToAdd[iNdEx])
			copy(dAtA[i:], m.MembersToAdd[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.MembersToAdd[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.GroupName) > 0 {
		i -= len(m.GroupName)
		copy(dAtA[i:], m.GroupName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.GroupName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.GroupOwner) > 0 {
		i -= len(m.GroupOwner)
		copy(dAtA[i:], m.GroupOwner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.GroupOwner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Operator) > 0 {
		i -= len(m.Operator)
		copy(dAtA[i:], m.Operator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Operator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgGroupMember) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgGroupMember) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgGroupMember) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.ExpirationTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ExpirationTime):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintTx(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x12
	if len(m.Member) > 0 {
		i -= len(m.Member)
		copy(dAtA[i:], m.Member)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Member)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateGroupV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.GroupName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Members) > 0 {
		for _, s := range m.Members {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.Extra)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.MembersWithExpiration) > 0 {
		for _, e := range m.MembersWithExpiration {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgUpdateGroupMemberV2) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Operator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.GroupOwner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.GroupName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.MembersToAdd) > 0 {
		for _, s := range m.MembersToAdd {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.MembersToDelete) > 0 {
		for _, s := range m.MembersToDelete {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if len(m.MembersWithExpiration) > 0 {
		for _, e := range m.MembersWithExpiration {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgGroupMember) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Member)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.ExpirationTime)
	n += 1 + l + sovTx(uint64(l))
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateGroupV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateGroupV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateGroupV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GroupName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Members", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Members = append(m.Members, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Extra", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Extra = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MembersWithExpiration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MembersWithExpiration = append(m.MembersWithExpiration, &MsgGroupMember{})
			if err := m.MembersWithExpiration[len(m.MembersWithExpiration)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateGroupMemberV2) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateGroupMemberV2: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateGroupMemberV2: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Operator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Operator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupOwner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GroupOwner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GroupName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GroupName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MembersToAdd", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MembersToAdd = append(m.MembersToAdd, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MembersToDelete", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MembersToDelete = append(m.MembersToDelete, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MembersWithExpiration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MembersWithExpiration = append(m.MembersWithExpiration, &MsgGroupMember{})
			if err := m.MembersWithExpiration[len(m.MembersWithExpiration)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgGroupMember) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgGroupMember: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgGroupMember: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Member", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Member = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpirationTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.ExpirationTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
